# ГГ Анастасия
photo1 = str('AgACAgIAAxkBAAMQZB3jJyGOdGS0i8reu9Ka12LBolIAAnTFMRs42_BI5jvsI6KnguUBAAMCAAN4AAMvBA')
# Говорит по телефну1
photo2 = str('AgACAgIAAxkBAAIQSGRBtk2KyRo9OwmawBWvntux_G81AAIHwjEbA4sRSp3NL24U6qnsAQADAgADeAADLwQ')
# Ты уже подъехал. Я как раз нашла лесника. Сейчас он подойдёт
photo3 = str('AgACAgIAAxkBAAIQSWRBt4d_tunfP-Tbgt06t1JD_IhIAAIIwjEbA4sRSvNEund3BN-rAQADAgADeAADLwQ')
# Ну чё, погнали к кормушке!!!
photo4 = str('AgACAgIAAxkBAAIQS2RBucDBwmqgfTACzt6EkjPDk3RVAAIUwjEbA4sRStNbLsZwcwe1AQADAgADeAADLwQ')
# Позвонила леснику. Сказал встретиться с ним здесь.
photo5 = str('AgACAgIAAxkBAAIQTWRBuz-vzPrc76g7zHm22jjJyXrPAAIWwjEbA4sRSmQM2Fe-S6BRAQADAgADeAADLwQ')
# Давай только не быстро, чтоб мы успевали
photo6 = str('AgACAgIAAxkBAAIQe2RGbpQI4RxNldL13GyAOWYP13NcAAI-yzEbFoQ5SqxNbIbzjVEsAQADAgADeAADLwQ')
# Чего-то не видно никого
photo7 = str('AgACAgIAAxkBAAIQfGRGcSGRxg5-SlZVj7-j5fze_Z-AAAJKyzEbFoQ5Sge_7jRwPrVzAQADAgADeAADLwQ')
photo8 = str('AgACAgIAAxkBAAIQfmRGiKQI9EKHCuXygfiRX8Qo3d2ZAALwyzEbFoQ5SgUtYEbiDI_IAQADAgADeAADLwQ')
photo9 = str('AgACAgIAAxkBAAIQqGRG1XWcNUzmxyV-SWWZmkhARe6jAAI1zjEbFoQ5SoR7sCnPTUREAQADAgADeAADLwQ')
photo10 = str('AgACAgIAAxkBAAIQqmRG2hBciZ8LZveHSDw0MXvmyTHMAAJMzjEbFoQ5Sr5-Wmy8G8sJAQADAgADeAADLwQ')
photo11 = str('AgACAgIAAxkBAAIQrGRG3DljKq0txRQdanb3NetFSFi7AAJTzjEbFoQ5SjGWCGuWooNDAQADAgADeAADLwQ')
photo12 = str('AgACAgIAAxkBAAIQr2RG5TA0otL2GUe5rwjxD3uMAzI7AAKFzjEbFoQ5Sh6LvsEn7d7oAQADAgADeAADLwQ')
photo13 = str('AgACAgIAAxkBAAIQsWRG5ldQu3TWd0Z6D24BTI8t8bxTAAKQzjEbFoQ5SryG41ZvYrE2AQADAgADeAADLwQ')
photo14 = str('AgACAgIAAxkBAAIQs2RG7ULEMSRnwAjqgR7tqUX08OGFAAKgzjEbFoQ5StyrvOzfahHuAQADAgADeAADLwQ')
photo15 = str('AgACAgIAAxkBAAIQtWRG7-vhl5aYUPNTBtahOS4BSkhGAAJPzzEbFoQ5SoSnFZ3FVPeOAQADAgADeAADLwQ')
photo16 = str('AgACAgIAAxkBAAIQu2RG9o49NHKP9ciigeeJ50jAveBQAAJ8zzEbFoQ5So37XyyDgav_AQADAgADeAADLwQ')
photo17 = str('AgACAgIAAxkBAAIQ9GRHlGYrbyf_eecKD45wyo_43rpFAAKSxzEbFoRBSsQqlnkChfbWAQADAgADeAADLwQ')
photo18 = str('AgACAgIAAxkBAAIQ9mRHljPNUUagIajvFMavKxye8Bf3AAKexzEbFoRBSkahGKraN_HFAQADAgADeAADLwQ')
photo19 = str('AgACAgIAAxkBAAIQ-mRHo3zyWi_Mbwmhh9I2CjC-rp--AAIkyDEbFoRBSoBweg9E-rXwAQADAgADeAADLwQ')
photo20 = str('AgACAgIAAxkBAAIQ_GRHsbY9km2u6FddvR8osN1NmAMYAAKWyDEbFoRBSn-uQscUjGIEAQADAgADeAADLwQ')
photo21 = str('AgACAgIAAxkBAAIQ_mRHug4YgXzD-FrGMI6SVVjZPlL4AALSyDEbFoRBSpaxsE0AATfSVQEAAwIAA3gAAy8E')
photo22 = str('AgACAgIAAxkBAAIRCGRHwTf2Ra7yNmTutBqRNr4MChQXAALuyDEbFoRBSsC7Rzfyy1K4AQADAgADeAADLwQ')
photo23 = str('AgACAgIAAxkBAAIRBmRHwRALbNa9yLeLDLEBs3bRVdBqAALtyDEbFoRBSv0IJx7KY1XZAQADAgADeAADLwQ')
photo24 = str('AgACAgIAAxkBAAIREGRIJHtCGRV0a__qOhE4MU1X791FAALSyzEbFoRBSiUz29TUXjllAQADAgADeAADLwQ')
photo25 = str('AgACAgIAAxkBAAIREmRIJLdzMupa92KJqe2EaoUJvHGaAALTyzEbFoRBSn8BbTAAAWwP1wEAAwIAA3gAAy8E')
photo26 = str('AgACAgIAAxkBAAIRFGRIJMuExg-rSizXrmeMG3-6KNhiAALUyzEbFoRBSpmgxEg3Oe-TAQADAgADeAADLwQ')
photo27 = str('AgACAgIAAxkBAAIRFmRIJ-pmeaabv_DVBnbKAvI508eKAALayzEbFoRBSlYV4X4ZaPg4AQADAgADeAADLwQ')
photo28 = str('AgACAgIAAxkBAAIRGGRIKBINC5ieW2MhXvZFOFSC4JqHAALcyzEbFoRBSi2G9iflo7RHAQADAgADeAADLwQ')
photo29 = str('AgACAgIAAxkBAAIRGmRIK6YT-xXRrMRETnCHAAEp-sD4BwAC5ssxGxaEQUohceW8jOV10QEAAwIAA3gAAy8E')
# ареал мероприятия
map = str('AgACAgIAAxkBAAPSZCGOBt1nTCmGBCtfBzxB98H87gkAApvGMRugYAhJH-AcZQiX3HEBAAMCAAN4AAMvBA')
# лесник
lesnik = str('AgACAgIAAxkBAAIQSmRBuL7HKGP_Qy3bHhzNr8vapklFAAIRwjEbA4sRShLiE78JNew0AQADAgADeAADLwQ')
# Тогда сгоняйте на кормушку, отвезите туда соли. Как справитесь , звоните скажу куда подъехать.
lesnik2 = str('AgACAgIAAxkBAAIQTGRBuoJBiScGHPeJHdI3ZR0XFfr1AAIVwjEbA4sRSuYGOVUwzzk3AQADAgADeAADLwQ')
# Частенько я мужика которого вы ищете у старого колодца встречаю. Сдесь не далеко. Давайте за мной
lesnik3 = str('AgACAgIAAxkBAAIQTmRBvD1O9MpzaKEJHGUa4RPq-TUVAAIXwjEbA4sRSgZnivTXVFpRAQADAgADeAADLwQ')
lesnik4 = str('AgACAgIAAxkBAAIQf2RGinj6rBVuR9J8pNBLIy8Rj2HVAAL9yzEbFoQ5SkBKXTtEb35VAQADAgADeAADLwQ')

sergey = str('AgACAgIAAxkBAAIQrmRG4O8vtolMWEOH-cDRknw6e9qrAAJ7zjEbFoQ5StqOXOd52i0fAQADAgADeAADLwQ')
rybar1 = str('AgACAgIAAxkBAAIQt2RG8ZCsd6cs4nIwDwABunI9cr9VbwACac8xGxaEOUrtIzXiH0fw8AEAAwIAA3gAAy8E')
rybar2 = str('AgACAgIAAxkBAAIQuWRG8biHxH-e5u7ErzMCDTLloKZTAAJqzzEbFoQ5StT1btimjNOxAQADAgADeAADLwQ')
vasya = str('AgACAgIAAxkBAAIQ-GRHmVorgYEu8kx5pmswIWZ_mqCPAAK7xzEbFoRBSrfDyrBZ8oSMAQADAgADeAADLwQ')
watchman = str('AgACAgIAAxkBAAIRAAFkR7w0ou9uGh90ajFZZJ_I9Jk5qgAC2cgxGxaEQUppDzyu-LcBjQEAAwIAA3gAAy8E')
watchman2 = str('AgACAgIAAxkBAAIRAmRHvFI-40zQM2QEfy8TCfEfJSjQAALayDEbFoRBSh1VFSk9LUM9AQADAgADeAADLwQ')
watchman3 = str('AgACAgIAAxkBAAIRBGRHvG9IqQV0f-9fVmcVOrjsrLb7AALcyDEbFoRBSpxRwUIgWB2HAQADAgADeAADLwQ')
watchman4 = str('AgACAgIAAxkBAAIRCmRIIG6udPjmXxaFRDVX_tkIDog-AAKxyzEbFoRBSoXrJt6pS85SAQADAgADeAADLwQ')
watchman5 = str('AgACAgIAAxkBAAIRDGRIIJsbkPHqmteZuJBvs0b7fPdfAAKyyzEbFoRBSvgv5KPy_Re0AQADAgADeAADLwQ')
watchman6 = str('AgACAgIAAxkBAAIRDmRIIURJyqG2HRLUPsBThacYXA60AAK1yzEbFoRBShy6rL9xK7fUAQADAgADeAADLwQ')